# -*- coding: utf-8 -*-
"""Assignment 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G5XZ5-k_Um4cPTwawZM1mRvT_vVKz2j0
"""

class Person():
  def __init__(self, name, age, mno):
   self.name = name
   self.age = age
   self.matric_number = mno

  def display(self):
    print("name", self.name)
    print("age", self.age)
    print("matric_number", self.matric_number)

  def __str__(self):
    return f"Name: {self.name}, Age: ({self.age}), Matric_number: ({self.matric_number})"

class Student(Person):
 pass

s1=Student("Puteri", 22, "1819670")
s1.display()

