# -*- coding: utf-8 -*-
"""Assignment 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D3Zq7-VBQBbyxNHBDGvbMZvRlAF3kex_
"""

value = [25, 35, 15, 40, 18]
largest_number = value[0]

for x in value:
 if x > largest_number:
  largest_number = x
  
print(largest_number)

